INSERT INTO user(user_type, id, name, uid, email, image_url) VALUES ('user', 1, 'Francisco', 'abc', 'email1', 'image_url1')
INSERT INTO user(user_type, id, name, uid, email, image_url) VALUES ('admin', 2, 'Francisco', 'abcd', 'email2', 'image_url2')
INSERT INTO user(user_type, id, name, uid, email, image_url) VALUES ('user', 3, 'Roque', 'roque', 'email3', 'image_url3')
INSERT INTO tag(id, name) VALUES (1, 'tag1')
INSERT INTO tag(id, name) VALUES (2, 'tag2')
INSERT INTO topic(id, title, state, description, user_id) VALUES (1, 'title_topic1',true, 'description_topic1', 1)
INSERT INTO topic(id, title, state, description, user_id) VALUES (2, 'title_topic2',true,'description_topic2', 2)
INSERT INTO post(id, content, name, topic_id, user_id) VALUES (1, 'content1', 'post1', 1, 1)
INSERT INTO post(id, content, name, topic_id, user_id) VALUES (2, 'content2', 'post2', 2, 1)
INSERT INTO topic_tags(topic_id, tag_id) VALUES (1, 1)
INSERT INTO topic_tags(topic_id, tag_id) VALUES (1, 2)
INSERT INTO topic_tags(topic_id, tag_id) VALUES (2, 1)
INSERT INTO comment(id, text, user_id, post_id) VALUES (1, 'hello_world', 1, 2)
INSERT INTO comment(id, text, user_id, post_id) VALUES (2, 'hello_world2', 2, 2)
INSERT INTO comment(id, text, user_id, post_id) VALUES (3, 'hello_world3', 2, 1)
INSERT INTO comment(id, text, user_id, post_id) VALUES (4, 'hello_world4', 1, 1)